/**
 * Pure, multi-player Yahtzee rules on top of the shared {@link TurnRules} model.
 *
 * Following the dice-game pattern (Ludo/Goose), **rolling is a phase**, not a
 * move: the only enumerable move is *scoring a category*, so `legalMoves` stays
 * finite and the host-authoritative relay can gate it. The randomness of a roll
 * is applied by {@link applyRoll} with dice the acting client already generated,
 * keeping `applyMove` deterministic and unit-testable.
 */
import { TurnRules, Seat } from '../../shared/turn/turnGame.js';
import { Die, ScoreKey, ALL_KEYS, scoreFor, grandTotal } from './yahtzee.js';

export const ROLLS_PER_TURN = 3;

export interface YState {
  players: number;
  seat: Seat;
  dice: Die[];
  rollsLeft: number;
  /** Whether the current seat has rolled at least once (can't score before). */
  rolledThisTurn: boolean;
  /** One scorecard per player. */
  cards: Partial<Record<ScoreKey, number>>[];
}

/** The only move: commit the current dice to one still-empty category. */
export type YMove = { category: ScoreKey };

/** A player's total once (or before) their card is complete. */
export function totalFor(card: Partial<Record<ScoreKey, number>>): number {
  return grandTotal(card, 0);
}

/** Applies a roll (dice already generated by the acting client). Pure. */
export function applyRoll(state: YState, dice: Die[]): YState {
  return {
    ...state,
    dice: [...dice],
    rollsLeft: Math.max(0, state.rollsLeft - 1),
    rolledThisTurn: true,
  };
}

export class YahtzeeRules implements TurnRules<YState, YMove> {
  readonly seats: number;

  constructor(players = 2) {
    this.seats = players;
  }

  initialState(): YState {
    return {
      players: this.seats,
      seat: 0,
      dice: [1, 1, 1, 1, 1],
      rollsLeft: ROLLS_PER_TURN,
      rolledThisTurn: false,
      cards: Array.from({ length: this.seats }, () => ({}) as Partial<Record<ScoreKey, number>>),
    };
  }

  currentSeat(state: YState): Seat {
    return state.seat;
  }

  /** The still-empty categories for the seat to play (scoring is finite). */
  legalMoves(state: YState): YMove[] {
    if (this.winner(state) !== null) return [];
    const card = state.cards[state.seat];
    return ALL_KEYS.filter((k) => !(k in card)).map((category) => ({ category }));
  }

  applyMove(state: YState, move: YMove): YState {
    const seat = state.seat;
    const cards = state.cards.map((c, i) =>
      i === seat ? { ...c, [move.category]: scoreFor(move.category, state.dice) } : c
    );
    return {
      ...state,
      cards,
      seat: (seat + 1) % state.players,
      dice: [1, 1, 1, 1, 1],
      rollsLeft: ROLLS_PER_TURN,
      rolledThisTurn: false,
    };
  }

  winner(state: YState): Seat | null {
    const done = state.cards.every((c) => ALL_KEYS.every((k) => k in c));
    if (!done) return null;
    const totals = state.cards.map(totalFor);
    const best = Math.max(...totals);
    if (totals.filter((t) => t === best).length > 1) return null; // tie
    return totals.indexOf(best);
  }
}
